# Alacritty Configuration
# Gruvbox Material Dark Hard Theme with JetBrains Nerd Font

# Window configuration
[window.padding]
x = 10
y = 10

[window]
# Fix extra padding issues with applications like Neovim
dynamic_padding = true
resize_increments = true


# Font configuration
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font]
size = 11.0

# Font spacing adjustments (acts like internal margins)
[font.offset]
x = 0          # Horizontal character offset
y = 1          # Vertical character offset (slight spacing)

[font.glyph_offset]
x = 0          # Individual glyph x offset
y = 0          # Individual glyph y offset

[colors]
# Gruvbox Material Dark Hard Theme
[colors.primary]
background = "#1d2021"  # Dark hard background
foreground = "#d4be98"  # Gruvbox Material foreground

[colors.normal]
black   = "#1d2021"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#d4be98"

[colors.bright]
black   = "#665c54"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#d4be98"