############################### Auwindowrulev2 = pin, title:^(Picture-in-Picture)$

# Authentication dialogs
windowrulev2 = float, class:^(polkit-gnome-authentication-agent-1)$
windowrulev2 = dimaround, class:^(polkit-gnome-authentication-agent-1)$



# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█ialogs
windowrulev2 = float, class:^(polkit-gnome-authentication-agent-1)$
windowrulev2 = dimaround, class:^(polkit-gnome-authentication-agent-1)$



# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█ AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules


# Window rules for common applications
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
windowrule = idleinhibit fullscreen, class:^(.*LibreWolf.*)$|^(.*floorp.*)$|^(.*Brave.*)$|^(.*firefox.*)$|^(.*chromium.*)$|^(.*zen.*)$|^(.*vivaldi.*)$

# Float certain windows
# windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float,class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = minsize 650 400,class:^(org.pulseaudio.pavucontrol)$ 

windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, class:^(nm-applet)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = float, class:^(org.kde.polkit-kde-authentication-agent-1)$

# Thunar file manager specific rules  
windowrulev2 = float, class:^(nemo)$, title:^(File Operation Progress)$
windowrulev2 = float, class:^(nemo)$, title:^(Confirm to replace files)$

# Picture-in-picture windows
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$

# Authentication dialogs
windowrulev2 = float, class:^(polkit-gnome-authentication-agent-1)$
windowrulev2 = dimaround, class:^(polkit-gnome-authentication-agent-1)$ 



# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule = blur,rofi
layerrule = blur,waybar